worker_processes auto;
pid /run/nginx.pid;
include /etc/nginx/modules-enabled/*.conf;

events {
    worker_connections 768;
}

http {
    sendfile on;
    tcp_nopush on;
    types_hash_max_size 2048;

    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    server_tokens off;
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
    gzip_min_length 1000;

    access_log /dev/stdout;
    error_log /dev/stderr;

    server {
        listen 80;
        server_name localhost;
        root /var/www/html;
        index index.html index.php;

        location / {
            try_files $uri $uri/ /index.html;
        }

        location ^~ /static/ {
            add_header Cache-Control "public, max-age=31536000, immutable";
        }

        location ~ \.php$ {
            fastcgi_pass 127.0.0.1:9000;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            include fastcgi_params;
        }

    }
}
